services:
  backend:
    build: . 
    ports:
      - '16485:8000'
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 8000
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
  
